using QualityGate.Domain;
using QualityGate.Infrastructure.Coverage;

namespace QualityGate.Gates;

public sealed class CoverageGate : IQualityGate
{
    private readonly ICoverageParser _coverageParser;

    public string Name => "Coverage";

    public CoverageGate(ICoverageParser coverageParser)
    {
        _coverageParser = coverageParser ?? throw new ArgumentNullException(nameof(coverageParser));
    }

    public async Task<GateResult> ExecuteAsync(QualityContext context, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(context);

        var coverageFiles = Directory.Exists(context.ArtifactDirectory)
            ? Directory.GetFiles(context.ArtifactDirectory, "coverage.cobertura.xml", SearchOption.AllDirectories)
            : [];

        if (coverageFiles.Length == 0)
        {
            if (context.TestProjects.Count > 0 && context.Options.Execution.UnitTests)
            {
                return GateResult.Fail(
                    Name,
                    "No coverage report was generated by the test runner.",
                    TimeSpan.Zero,
                    [new GateFinding("MissingCoverage", "Test execution completed without producing a coverage report.", "Error")]);
            }

            return GateResult.NotApplicable(Name, "No coverage reports available to evaluate.");
        }

        var summary = await _coverageParser.ParseMultipleAsync(coverageFiles, cancellationToken).ConfigureAwait(false);

        if (context.Target.Scope == QualityScope.Diff && context.ChangeSet != null)
        {
            return EvaluateDiffCoverage(context, summary);
        }

        return EvaluateGlobalCoverage(context, summary);
    }

    private GateResult EvaluateDiffCoverage(QualityContext context, CoverageSummary summary)
    {
        var ignorePatterns = (context.Options.ChangedCode.IgnorePatterns ?? [])
            .Concat(context.Options.IgnorePatterns ?? [])
            .Distinct();

        var changedFiles = GeneratedCodeFilter.FilterFiles(context.ChangeSet!.CSharpSourceFiles, ignorePatterns);
        if (changedFiles.Count == 0)
        {
            return GateResult.NotApplicable(Name, "No C# source files changed in this diff (or all changed files were ignored).");
        }

        var threshold = context.Options.ChangedCode.LineCoverage ?? 80m;
        var branchThreshold = context.Options.ChangedCode.BranchCoverage ?? 70m;

        int changedLinesValid = 0;
        int changedLinesCovered = 0;
        int changedBranchesValid = 0;
        int changedBranchesCovered = 0;
        var findings = new List<GateFinding>();

        foreach (var changedFile in changedFiles)
        {
            var match = summary.FileReports.FirstOrDefault(r =>
                r.Key.EndsWith(changedFile.Path, StringComparison.OrdinalIgnoreCase) ||
                changedFile.Path.EndsWith(r.Key, StringComparison.OrdinalIgnoreCase));

            if (match.Value != null)
            {
                var fileReport = match.Value;
                changedLinesValid += fileReport.LinesValid;
                changedLinesCovered += fileReport.LinesCovered;
                changedBranchesValid += fileReport.BranchesValid;
                changedBranchesCovered += fileReport.BranchesCovered;

                var uncoveredLines = fileReport.Lines.Values.Where(l => !l.IsCovered).Select(l => l.LineNumber).ToList();
                if (uncoveredLines.Count > 0 && fileReport.LineRate < threshold)
                {
                    var lineListStr = string.Join(", ", uncoveredLines.Take(10));
                    if (uncoveredLines.Count > 10) lineListStr += "...";

                    findings.Add(new GateFinding(
                        "Coverage",
                        $"{fileReport.LinesCovered} of {fileReport.LinesValid} executable lines are covered ({fileReport.LineRate:0.#}%). Uncovered lines: {lineListStr}",
                        "Error",
                        changedFile.Path,
                        actual: fileReport.LineRate,
                        threshold: threshold));
                }
            }
        }

        if (changedLinesValid == 0)
        {
            return GateResult.NotApplicable(Name, "No executable lines found in changed C# files.");
        }

        decimal actualLineCoverage = Math.Round((decimal)changedLinesCovered / changedLinesValid * 100m, 1);
        bool lineCoveragePassed = actualLineCoverage >= threshold;

        decimal actualBranchCoverage = changedBranchesValid > 0
            ? Math.Round((decimal)changedBranchesCovered / changedBranchesValid * 100m, 1)
            : 100m;
        bool branchCoveragePassed = actualBranchCoverage >= branchThreshold;

        if (!lineCoveragePassed || !branchCoveragePassed)
        {
            string failMsg = !lineCoveragePassed
                ? $"Changed line coverage {actualLineCoverage:0.#}% is below threshold {threshold:0.#}%."
                : $"Changed branch coverage {actualBranchCoverage:0.#}% is below threshold {branchThreshold:0.#}%.";

            return GateResult.Fail(
                Name,
                failMsg,
                TimeSpan.Zero,
                findings,
                actual: actualLineCoverage,
                threshold: threshold);
        }

        return GateResult.Pass(
            Name,
            $"Changed line coverage is {actualLineCoverage:0.#}% (threshold: {threshold:0.#}%).",
            TimeSpan.Zero,
            findings,
            actual: actualLineCoverage,
            threshold: threshold);
    }

    private GateResult EvaluateGlobalCoverage(QualityContext context, CoverageSummary summary)
    {
        var globalLineThreshold = context.Options.Global.LineCoverage;
        var globalBranchThreshold = context.Options.Global.BranchCoverage;

        if (!globalLineThreshold.HasValue && !globalBranchThreshold.HasValue)
        {
            // If no global threshold configured, pass with informational metric
            return GateResult.Pass(
                Name,
                $"Global line coverage is {summary.LineRate:0.#}%.",
                TimeSpan.Zero,
                actual: summary.LineRate);
        }

        var threshold = globalLineThreshold ?? 80m;
        decimal actualCoverage = Math.Round(summary.LineRate, 1);

        if (actualCoverage < threshold)
        {
            return GateResult.Fail(
                Name,
                $"Global line coverage {actualCoverage:0.#}% is below threshold {threshold:0.#}%.",
                TimeSpan.Zero,
                actual: actualCoverage,
                threshold: threshold);
        }

        return GateResult.Pass(
            Name,
            $"Global line coverage is {actualCoverage:0.#}% (threshold: {threshold:0.#}%).",
            TimeSpan.Zero,
            actual: actualCoverage,
            threshold: threshold);
    }
}
